<a href="https://colab.research.google.com/github/shreybhate09/website/blob/master/102_checkpoint2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from sklearn.linear_model import LogisticRegression as LR
from scipy import stats 
import pickle
from datascience import *
#import pymc3 as pm 
#from pymc3 import * 
%matplotlib inline
import seaborn as sns

In [2]:
dem_raw = "https://raw.githubusercontent.com/prasannguruprasad/d102-final-project/main/dem_candidates.csv"

In [ ]:
df = pd.read_csv(dem_raw,index_col=0,parse_dates=[0])

In [ ]:
df.iloc[:,10:20]

,Won Primary,Race,Veteran?,LGBTQ?,Elected Official?,Self-Funder?,STEM?,Obama Alum?,Party Support?,Emily Endorsed?
Candidate,,,,,,,,,,
Anthony White (Alabama),No,Nonwhite,Yes,No,No,No,No,No,NaN,NaN
Christopher Countryman,No,White,No,Yes,No,No,No,No,NaN,NaN
"Doug ""New Blue"" Smith",No,White,Yes,No,No,No,No,No,NaN,NaN
James C. Fields,No,Nonwhite,Yes,No,Yes,No,No,No,NaN,NaN
Sue Bell Cobb,No,White,No,No,Yes,No,No,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
Talley Sergent,Yes,White,No,No,No,No,No,Yes,NaN,NaN
Janice Hagerman,No,White,No,No,No,No,No,No,NaN,NaN
Paul Davis,No,White,No,No,No,No,No,No,NaN,NaN
Richard Ojeda,Yes,Nonwhite,Yes,No,Yes,No,No,No,NaN,NaN
Shirley Love,No,White,No,No,No,No,No,No,NaN,NaN

In [ ]:
race = df.iloc[:,11].sample(811).values
shuffled = pd.DataFrame(df.index, race)
shuffled.head()

                             0
Candidate
Anthony White (Alabama)  White
Christopher Countryman     NaN
Doug "New Blue" Smith    White
James C. Fields          White
Sue Bell Cobb            White

In [ ]:
def ab_test(id):
  shuffled = df.iloc[:,id].sample(len(df)).values
  

for i in range(1000):

<ipython-input-78-a707df892455>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  shuffled = pd.DataFrame(reconfig).groupby("identifier").mean().values

TypeError: ignored

In [ ]:
pd.DataFrame(df.key)

In [ ]:
df.index

Index(['Anthony White (Alabama)', 'Christopher Countryman',
       'Doug "New Blue" Smith', 'James C. Fields', 'Sue Bell Cobb',
       'Walt Maddox', 'Lizzetta Hill McConnell', 'Robert Kennedy Jr.',
       'Audri Scott Williams', 'Tabitha Isner',
       ...
       'Thomas Cramer', 'Kendra Fershee', 'Ralph Baxter', 'Tom Payne',
       'Aaron Scheinberg', 'Talley Sergent', 'Janice Hagerman', 'Paul Davis',
       'Richard Ojeda', 'Shirley Love'],
      dtype='object', name='Candidate', length=811)